### PR TITLE
Watir site redesign.kiiingbob

### PR DESCRIPTION
**Pull request by thekiiingbob**
All advanced interactions should be included in this PR.

The information is cobbled together from the various existing sites.

There are major structural changes to how the documentation is organized and how it's all put together. The gist is that all of the docs live in /_docs. You can add additional pages to this directory, and update the _data/docs.yml file to include them in the sidebar.

I'm of course open to any suggestions. :)

### CODE REVIEW

**Comment by abaird** [comment]
how do you preview these changes?

**Comment by thekiiingbob** [comment]
You should just need
`gem install github-pages`
and then
`jekyll serve`
and then you can hit http://127.0.0.1:4000/ to view.

**Comment by bret** [comment]
I think it is premature to tout the extensibility of Watir before we actually figure out how this is going to work. I like the design and format and spirit, however.

**Comment by bret** [comment]
Ok, looked at the pull request more closely. I now see that most of this is migration of content (which i think needs no discussion), but there is also the homepage changes that i think we need to discuss more. Would it be possible to separate these into two pull requests?

**Comment by thekiiingbob** [comment]
Sure thing. I'll split it into homepage and content.

**Comment by thekiiingbob** [comment]
Closing this PR to make way for the two seperate ones.

**Pull request closed without merging**
