### PR TITLE
change docs to articles

### PR DESCRIPTION
**Pull request by titusfortner**
There has been some confusion on the function of the "documentation" on our site versus the "documentation" on rubydocs.

I propose we rename "documentation" to "articles" on the site, and make sure we reference the documentation on rubydocs (especially since it is really good).

I considered "guides" but "technical articles" seemed better to me? Easy enough to change if we want to go that route instead.

### CODE REVIEW

**Comment by jaysonesmith** [comment]
That's a tough one. I like the idea of 'guides' and also 'examples' but not everything fits in 'examples' so we'd need to split or something. Articles work though!

**Comment by titusfortner** [comment]
I guess I'm looking at it like this:
* Documentation: in the code itself and presented on RubyDocs
* Technical Articles: descriptions with examples of how to do common things
* Tutorials: step by step walkthrough of how to accomplish something specific

I'm thinking that anything we might put on YouTube with a video walk through of something would go in the tutorial section, whether it is actually on YouTube or just spelled out in text with code. :)

"Guides" seems to straddle articles and tutorials in a way that makes less sense to me.

**Comment by titusfortner** [comment]
Also, I added a commit that puts a link on each site to make it easy to edit the page on github.

**Comment by jaysonesmith** [comment]
:+1: !

**Comment by jaysonesmith** [comment]
YT tuts seem neat

**Comment by abaird** [comment]
> I guess I'm looking at it like this:

> Documentation: in the code itself and presented on RubyDocs
> Technical Articles: descriptions with examples of how to do common things
> Tutorials: step by step walkthrough of how to accomplish something specific

I like guides better. Article makes me think of a blog post or something or an external resource.

**Comment by titusfortner** [comment]
Lol, that's *exactly what @thekiiingbob said. Ok, I'll change it.

**Pull request merged**
